### ISSUE TITLE
Fonts configuration issue

### ISSUE THREAD

**Issue by edvorg** [techquila/melancholy-theme#3]
Hi, very nice colors. But is it possible not to redefine default fonts in this theme?
I bet many people use something different than dejavu family fonts.
Also they probably configure it themselves.
E.g. my configuration has some tweaks to make themes good-looking on retina display and make it monospaced everywhere. But this theme makes the font very big and non-monospaced.
What do you think? Thanks.

**Comment by techquila** [comment]
Hey there, thanks for your comments.

This theme kind of came about from me wanting a bit of a change from the dull monospace world I lived in, to something a little more colourful and modern.  I was also consciously attempting to separate all style related config into one file like a style sheet as that felt like a logical separation of concerns to me.

It's still in its infancy but I hope to further refine the fonts and typographic selections over the next few weeks and will refactor as I learn better ways of doing things.  The point of difference for this theme should be its use of colour and typography though I reckon.

**Comment by techquila** [comment]
thinking out loud here but there may be some benefit to including some logic within the theme that provides the user with the capability to cycle through sans => serif => monospace fonts.

In any case it looks like @xahlee solved this issue for us already anyways:
http://ergoemacs.org/emacs/emacs_switching_fonts.html

I'll have a play around with it over this weekend and see if i can improve things.

**Comment by xahlee** [comment]
nice theme, and, melancholy, nice name. :+1:

**Comment by techquila** [comment]
thanks Xah!
